default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: live_coding_development

test:
  <<: *default
  database: live_coding_test

production:
  <<: *default
  database: live_coding_production
  username: live_coding
  password: <%= ENV['LIVE_CODING_DATABASE_PASSWORD'] %>
